name: tests

on:
  push:
  pull_request:

jobs:
  simulate:
    runs-on: ubuntu-24.04
    steps:
      - name: Get the code
        uses: actions/checkout@v5

      - name: Install Icarus Verilog and the RISC V compiler
        run: sudo apt-get update && sudo apt-get install -y iverilog gcc-riscv64-unknown-elf

      - name: Run all test suites
        run: make test RISCV_PREFIX=riscv64-unknown-elf-